# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: addressbook.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'addressbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64ressbook.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n\x06Person\x12\x12\n\x05\x65mail\x18\x01 \x01(\tB\x03\x80\x01\x01\x12#\n\x06phones\x18\x02 \x03(\x0b\x32\x13.Person.PhoneNumber\x1a\x97\x01\n\x0bPhoneNumber\x12\x13\n\x06number\x18\x01 \x01(\tB\x03\x80\x01\x01\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.Person.PhoneNumber.Type\"K\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTYPE_MOBILE\x10\x01\x12\r\n\tTYPE_HOME\x10\x02\x12\r\n\tTYPE_WORK\x10\x03\"\xce\x02\n\x07\x43ompany\x12%\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x15.Company.EmailAddress\x12$\n\x06phones\x18\x02 \x03(\x0b\x32\x14.Company.PhoneNumber\x1aK\n\x0c\x45mailAddress\x12\x12\n\x05\x65mail\x18\x01 \x01(\tB\x03\x80\x01\x01\x12\'\n\ndepartment\x18\x02 \x01(\x0e\x32\x13.Company.Department\x1aK\n\x0bPhoneNumber\x12\x13\n\x06number\x18\x01 \x01(\tB\x03\x80\x01\x01\x12\'\n\ndepartment\x18\x02 \x01(\x0e\x32\x13.Company.Department\"\\\n\nDepartment\x12\x1a\n\x16\x44\x45PARTMENT_UNSPECIFIED\x10\x00\x12\x11\n\rDEPARTMENT_HR\x10\x01\x12\x1f\n\x1b\x44\x45PARTMENT_CUSTOMER_SERVICE\x10\x02\"{\n\x07\x43ontact\x12\x30\n\x0clast_updated\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x06person\x18\x02 \x01(\x0b\x32\x07.PersonH\x00\x12\x1b\n\x07\x63ompany\x18\x03 \x01(\x0b\x32\x08.CompanyH\x00\x42\x06\n\x04kind\"v\n\x0b\x41\x64\x64ressBook\x12,\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x1a.AddressBook.ContactsEntry\x1a\x39\n\rContactsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Contact:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addressbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON_PHONENUMBER'].fields_by_name['number']._loaded_options = None
  _globals['_PERSON_PHONENUMBER'].fields_by_name['number']._serialized_options = b'\200\001\001'
  _globals['_PERSON'].fields_by_name['email']._loaded_options = None
  _globals['_PERSON'].fields_by_name['email']._serialized_options = b'\200\001\001'
  _globals['_COMPANY_EMAILADDRESS'].fields_by_name['email']._loaded_options = None
  _globals['_COMPANY_EMAILADDRESS'].fields_by_name['email']._serialized_options = b'\200\001\001'
  _globals['_COMPANY_PHONENUMBER'].fields_by_name['number']._loaded_options = None
  _globals['_COMPANY_PHONENUMBER'].fields_by_name['number']._serialized_options = b'\200\001\001'
  _globals['_ADDRESSBOOK_CONTACTSENTRY']._loaded_options = None
  _globals['_ADDRESSBOOK_CONTACTSENTRY']._serialized_options = b'8\001'
  _globals['_PERSON']._serialized_start=55
  _globals['_PERSON']._serialized_end=274
  _globals['_PERSON_PHONENUMBER']._serialized_start=123
  _globals['_PERSON_PHONENUMBER']._serialized_end=274
  _globals['_PERSON_PHONENUMBER_TYPE']._serialized_start=199
  _globals['_PERSON_PHONENUMBER_TYPE']._serialized_end=274
  _globals['_COMPANY']._serialized_start=277
  _globals['_COMPANY']._serialized_end=611
  _globals['_COMPANY_EMAILADDRESS']._serialized_start=365
  _globals['_COMPANY_EMAILADDRESS']._serialized_end=440
  _globals['_COMPANY_PHONENUMBER']._serialized_start=442
  _globals['_COMPANY_PHONENUMBER']._serialized_end=517
  _globals['_COMPANY_DEPARTMENT']._serialized_start=519
  _globals['_COMPANY_DEPARTMENT']._serialized_end=611
  _globals['_CONTACT']._serialized_start=613
  _globals['_CONTACT']._serialized_end=736
  _globals['_ADDRESSBOOK']._serialized_start=738
  _globals['_ADDRESSBOOK']._serialized_end=856
  _globals['_ADDRESSBOOK_CONTACTSENTRY']._serialized_start=799
  _globals['_ADDRESSBOOK_CONTACTSENTRY']._serialized_end=856
# @@protoc_insertion_point(module_scope)
