[package]
name = "addressbook_1"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
prost = "0.13"
prost-types = "0.13"
chrono = "0.4.40"

[build-dependencies]
prost-build = "0.13.5"
